### ISSUE TITLE
import missing

### ISSUE THREAD

**Issue by dodler** [ddddwee1/sul#1]
missing random import in layers3.py?

**Comment by ddddwee1** [comment]
Could you specify the problem, i.e., in which line of the code?

**Comment by dodler** [comment]
https://github.com/ddddwee1/sul/blob/master/model3.py#L424 - i see  here use of random module, 
but I can't find import statement, and my ide also doesn't see it, maybe i miss something in environment?

**Comment by ddddwee1** [comment]
Thanks for the reminder! Issue is fixed already
